manifest_version = "0.0.0-alpha"

[library]
name = "library_name"
version = "1.2.3"
dependencies = ["dep1/2.4.6", "dep2/3.5.7"]
short_description = "" # less than 120 characters
long_description = ""
authors = [
    { name = 'dev name', emai = 'dev.name@email.com' },
    { name = 'another dev', emai = 'another.dev@email.com' },
]
maintainers = [
    { name = 'some maintainer', email = 'smaintainer@email.com' },
    { name = 'another maintainer', email = 'amaintainer@email.com' },
]
tags = ['tag', 'another-tag']
readme = "README.md"
license = { file = "license.txt", identifier = "Apache-2.0" }
# license = { text = "MIT License" }

[files]
scad = ["path/to/file.scad", "glob/pattern/to/some/*files.scad"]

[urls]
repository = "github.com/github/example"
homepage = "example.com"
documentation = "example.com"
