[tool.poetry]
name = "olman-models"
version = "0.1.0"
description = ""
authors = ["Jack OAT <jack.oat29@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "^2.8.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
